name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - develop
      - main
#  pull_request:
#    branches:
#      - develop
#      - main
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v6
        with:
          repository: paulocarvalho/php-8.4
          file: Dockerfile
          tags: paulocarvalho/php-8.4:latest
          push: true
